[tool.poetry]
name = "magiqtouch"
version = "0.1.0"
description = ""
authors = ["Andrew Leech <andrew@alelec.net>"]

[tool.poetry.dependencies]
python = "^3.8"
AWSIoTPythonSDK = "^1.4.9"
structured-config = "^4.12"
asyncio_mqtt = "^0.10.0"
mandate = { git = "https://github.com/andrewleech/mandate.git" }

#aiohttp = "^3.7.2"
#botocore = "^1.19.7"
#boto3 = "^1.19.7"
#awsiotsdk = "^1.5.1"
#pycognito = "^0.1.4"
#aiorequests = "^0.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
